directories:
  output: dist-cdn-first-fix
  buildResources: build
appId: com.eduvi.game
productName: EduVi Game
win:
  target:
    - portable
  icon: assets/icon.ico
files:
  - filter:
      - src/**/*
      - assets/**/*
extraResources:
  - from: assets/mediapipe
    to: mediapipe
electronVersion: 28.3.3
